import { Button } from "@components/Button";
import { Highlight } from "@components/Highlight";
import { HIGHLIGHT_COLOR } from "lib/constants";
import { RoughNotationGroup } from "lib/rough-notation";
import { useIsFontReady } from "lib/useIsFontReady";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  const isFontReady = useIsFontReady();

  return (
    <>
      <Head>
        <title>Santi Dalmasso</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="px-6">
        <div className="block">
          <div className="bg-hero absolute border-box inset-0 -z-1"></div>
          <section className="mx-auto max-w-screen-md mt-0 sm:mt-20 md:mt-40 py-20 px-4 sm:px-10">
            <RoughNotationGroup show={isFontReady}>
              <h1 className="text-2xl md:text-4xl font-md">
                Hi there, I&apos;m <strong>Santi Dalmasso</strong>.
              </h1>
              <div className="mt-4">
                <p>
                  I love improving and making people&apos;s lives easier by
                  developing technological solutions. I work as a&nbsp;
                  <Highlight color={HIGHLIGHT_COLOR}>
                    Full-Stack Developer
                  </Highlight>
                  &nbsp;at&nbsp;
                  <a
                    href="https://rooftop.dev"
                    className="font-bold filter grayscale brightness-0 dark:brightness-200 hover:filter-none text-rooftop duration-300"
                    target="blank"
                  >
                    <div className="inline-block align-middle">
                      <Image
                        src="/icons/rooftop.png"
                        height="22px"
                        width="22px"
                        alt="Rooftop logo"
                      />
                    </div>
                    &nbsp;Rooftop&nbsp;
                  </a>
                  — developing with react, node and typescript.
                </p>
                <p className="mt-2">
                  Currently I am finishing my studies in Information&nbsp;
                  <Highlight color={HIGHLIGHT_COLOR}>
                    Systems Engineering
                  </Highlight>
                  &nbsp;and trying to become a better developer as I grow in my
                  professional career.
                </p>
                <p className="mt-2">
                  I enjoy learning about new technologies and I am passionate
                  about web development.
                </p>
              </div>
            </RoughNotationGroup>
            <div className="mt-8 flex gap-5 w-full">
              <a
                href="https://github.com/santidalmasso"
                target="blank"
                className="w-full sm:w-36"
              >
                <Button className="w-full">View Github</Button>
              </a>
              <a
                href="https://www.linkedin.com/in/santiago-dalmasso-232448145/"
                className="w-full sm:w-36"
                target="blank"
              >
                <Button variant="secondary" className="w-full">
                  View Linkedin
                </Button>
              </a>
            </div>
          </section>
        </div>
      </main>
    </>
  );
}
