#!/bin/bash

echo -e "Building Staging environment files\n"

# Replace the staging index.html file with the index.template.html file
rm ./staging/index.html
cp ./index.template.html ./staging/index.html

# Compile dmm staging environment
node scripts/dmm_compile_vue_routes.js

# Compile Drash staging environment
node scripts/drash_compile_vue_routes.js

# Compile Rhum staging environment
node scripts/rhum_compile_vue_routes.js

# Compile Sockets staging environment
node scripts/sockets_compile_vue_routes.js

# Compile all html files for all modules
node scripts/compile_staging_html.js

# Build webpack bundles
node_modules/.bin/webpack --hide-modules --env.environment=staging

# Rebuild all previous versions of docs so that they include all versions in sidebar
. ./scripts/build_version rhum v1.1.4
