#!/bin/bash

ENVIRONMENT="$1"

echo -e "Building ${ENVIRONMENT} environment files\n"

# Replace appropriate index.html file with the index.template.html file

if [ $ENVIRONMENT == "production" ]; then
  rm ./index.html
  cp ./index.template.html ./index.html
elif [ $ENVIRONMENT == "staging" ]; then
  rm ./staging/index.html
  cp ./index.template.html ./staging/index.html
fi

scripts/compile_vue_routes

# Compile all html files for all modules
node "scripts/compile_${ENVIRONMENT}_html.js"

# Build webpack bundles
node_modules/.bin/webpack --hide-modules --env.environment=$ENVIRONMENT

# Rebuild all previous versions of docs so that they include all versions in sidebar

scripts/build_version dmm v1.2.0
scripts/build_version drash v1.3.0
scripts/build_version rhum v1.1.4
