#!/bin/bash

MODULE="$1"

if [ $MODULE ]; then
  node "scripts/${MODULE}_compile_vue_routes.js"
  exit
fi

node scripts/dmm_compile_vue_routes.js

node scripts/drash_compile_vue_routes.js

node scripts/rhum_compile_vue_routes.js

node scripts/sockets_compile_vue_routes.js
